### ISSUE TITLE
IDE should take a confirmation from the user about exiting the program

### ISSUE THREAD

**Issue by BerkUtkuYenisey** [kasirgalabs/ETUmulator#17]
IDE's like eclipse and Sublime Text takes a confirmation from the user to exit the program like:

"Are you sure to exit the program, all your unsaved changes will be lost."

After user clicks the red cross button(exit button at the top left corner). And gives to choices like "Yes" and "No". If user clicks yes then the program exits on close otherwise it does not.

**Comment by RootG** [comment]
Hello Berk,

Thank you for your interest but unfortunately someone has been working on a similar issue. For student projects please suggest your opinions via email.

**Comment by BerkUtkuYenisey** [comment]
Hello Gorkem,

You have said that someone is working on a similar issue but we have
limited time for this project and I am thinking a lot on finding new
issues. If someone has taken this issue why would he or she has not opened
it on GitHub. I have opened the issue and I have written the code for it
only the implementation is left. It is really disappointing for me to hear
that someone has taken a similar issue and now I am left issueless. It
would be very nice if you could help me with this matter or recommend me
some untaken issues.

Yours Sincerely,


Berk Utku YENİSEY

2018-03-07 22:54 GMT+03:00 Görkem Mülayim <notifications@github.com>:
