### ISSUE TITLE
A Built-In Example

### ISSUE THREAD

**Issue by RootG** [kasirgalabs/ETUmulator#5]
Add a built in example to ETUmulator, where user can open it by clicking on the toolbar menu. There is a simple Hello World Program on the website of [ETUmulator](https://kasirgalabs.github.io/ETUmulator/) which demonstrates a few basic instructions. For example, Hello World Program should be opened in the editor of ETUmulator by clicking "File > Examples > Hello World".

Although, it is not necessary to implement this feature with Hello World Program, implementer can include the program of his/her choice.

**Here is an image from Arduino IDE that shows how this feature should look like:**
![built_in_examples](https://user-images.githubusercontent.com/17679464/36898390-bfa08c80-1e2b-11e8-830a-49907d29b098.png)

**Comment by BurakDmb** [comment]
We would like to contribute on this project as a team with one of us assigned to this issue, currently waiting for your response

**Comment by doruksahin** [comment]
Hello :) Thanks for assigning me to that issue. I managed to add "Examples" Menu item on the bar. But I am not sure which instructions i should demonstrate.
![screenshot from 2018-03-26 04-10-42](https://user-images.githubusercontent.com/35743092/37882413-cd3069dc-30ab-11e8-8eb2-73a078c22e7a.png)
