### ISSUE TITLE
Implement Support for RBIT Instruction

### ISSUE THREAD

**Issue by RootG** [kasirgalabs/ETUmulator#7]
There is a similar structured instruction called RRX which can be emulated by ETUmulator. One can start by understanding how RRX instruction is implemented and emulated.

Please see [ARM and Thumb-2 Instruction Set Quick Reference Card](http://infocenter.arm.com/help/topic/com.arm.doc.qrc0001l/QRC0001_UAL.pdf) for more information about the instruction.

**Comment by unibodydesignn** [comment]
I would like to contribute on this issue, currently waiting for your response and permission.
