### ISSUE TITLE
Implement Support for BFC Instruction

### ISSUE THREAD

**Issue by RootG** [kasirgalabs/ETUmulator#8]
With a little help despite lack of similar structured instruction it would make it easier to add support for BFC instruction. Please first checkout the instruction from [ARM and Thumb-2 Instruction Set Quick Reference Card](http://infocenter.arm.com/help/topic/com.arm.doc.qrc0001l/QRC0001_UAL.pdf).

If the instruction defined like `BFC Rd, #<imm16>, #<imm8>` instead of `BFC Rd, #<lsb>, #<width>` it would be much more easier since `imm16` and `imm8` constant fields are already emulated. So, try adding parser rules that match`lsb` and `width` to make things easier. After that you can pick a instruction of your choice and see how it emulated in ETUmulator then move on writing some Java code.

Optional: It is stated that `<width>` + `<lsb>` must be `<= 32` but this requires quite understanding of how ETUmulator works. For simplicity, you can skip this part. If you are still up to implementing this constant validation you might want to understand how we process [registerShiftedByConstant](https://github.com/kasirgalabs/ETUmulator/blob/6ea0e35d2896fa1c4d45f21e6a67e39f28cd630c/src/main/antlr/Assembler.g4#L486).

- [ ] lsb and width parser rules
- [ ] lsb and width emulation
- [ ] Instruction support
- [ ] Constant validation

**Comment by BerkUtkuYenisey** [comment]
I would like to contribute to this issue, currently waiting for your permission.
